### ISSUE TITLE
simplify the injection of IAM / identity annotations into ServiceAccounts

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-gitops#142]
we currently have been using helm templating to inject GKE project ID / AWS account ID data into charts to enable IAM roles on kubernetes service accounts like this...
https://github.com/jenkins-x/jxr-versions/blob/ea2a49ac197c0763b7d01166b15e259e111ee33c/charts/jenkins-x/tekton/values.yaml.gotmpl#L18

its maybe more secure to have terraform generate the annotations we need on ServiceAccounts into a Secret which we can then read to enrich the service accounts without having to check the account ID / annotations into git.

e.g. maybe Terraform could generate a `Secret` in the `default` namespace called something like `jx-service-acount-annotations`

which can contain the annotations to add to the ServiceAccounts something like....

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: jx-service-account-annotations
  namespace: default
data:
  tekton-bot: |-
     eks.amazonaws.com/role-arn: arn:aws:iam::$accountID:role/$clusterName-$namespace-tekton-bot
  controllerbuild: |-
     eks.amazonaws.com/role-arn: arn:aws:iam::$accountID:role/$clusterName-$namespace-controllerbuild
```

then we can have a step in the boot pipeline to detect this `Secret` and apply any additional annotations to the `ServiceAcount` resources before they get applied?

This would simplify the need for conditional helm values file templating in the version stream / charts too
