### ISSUE TITLE
make `jx-apps.yml` explicit by default 

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-gitops#45]
this relates to #32 and #35 

it would be nice if all the configuration, versions, values files & templates were stored in the single git repository rather than be spread around (eg in the version stream)

It would be nice to have a command (say) `jx gitops apps resolve`  to resolve the version stream stuff up front...

* add any missing version numbers from the version stream (or have an upgrade mode to upgrade them if they are different in the version stream)
* copy any `values.yaml(.gotmpl)` files from the version stream if missing (using `kpt` to keep them in sync 
* add the `values.yaml(.gotmpl)` files into the `jx-apps.yml` file so it’s explicit what files will be passed into `helm template`

Eg if you start with a `jx-apps.yml` file like this in a mostly empty repository...

```yaml 
apps:
- name: jenkins-x/tekton
- name: jenkins-x/jxboot-helmfile-resources
- name: bitnami/external-dns
  namespace: foo
```

and ran `jx gitops apps resolve` it'd modify the file to something like:

```yaml 
apps:
- name: jenkins-x/tekton
  version: 1.2.3
  values:
  - helm-values/jenkins-x/tekton/values.yaml.gotmpl
- name: jenkins-x/jxboot-helmfile-resources
  values:
  - helm-values/jenkins-x/jxboot-helmfile-resources/values.yaml.gotmpl
  version: 4.5.6
- name: bitnami/external-dns
  namespace: foo
  version: 2.3.4
```

and it would create those values files on the local filesystem - grabbing them from the version stream - e.g. for [helm-values/jenkins-x/tekton/values.yaml.gotmpl](https://github.com/jenkins-x/jxr-versions/blob/master/apps/jenkins-x/tekton/values.yaml.gotmpl).

We're using a folder per chart to contain the `values.yaml` / `values.yaml.gotmpl` files so that we can easily use kpt to create the directory + grab the values files from the associated version stream folder.

then after the resolve has been done everything is local, declarative and clear & there’s no magic. Its obvious from the `jx-apps.yml` file all the values files/templates that will be used; what versions will be used etc

This would then simplify the `jx gitops apps template` command since it literally just iterates through the file and doing helm template with the given values files etc (evaluating any go templates before passing them into helm)
