### ISSUE TITLE
support custom group/organisation Settings in .jx/gitops/source-config

### ISSUE THREAD

**Issue by jstrachan** [jenkins-x/jx-gitops#701]
if you want to use, say, different github pages chart repositories for different github organisations it might be nice to configure those in the `.jx/gitops/source-config.yaml` file (see the [files reference](https://jenkins-x.io/v3/develop/reference/files/) to avoid folks having to add a `.jx/settings.yaml` file into each repository in a different organisation

e.g. in the dev git repository we could have something like...

```yaml
apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: owner1
    provider: https://github.com
    providerKind: github
    repositories:
    - name: foo
    - name: bar
    scheduler: in-repo
    settings:
      destination:
        chartRepository: https://github.com/owner1/charts.git
        chartKind: pages
  - owner: owner2
    provider: https://github.com
    providerKind: github
    repositories:
    - name: cheese
    scheduler: in-repo
    settings:
      destination:
        chartRepository: https://github.com/owner2/charts.git
        chartKind: page
```
