### ISSUE TITLE
add support for remote helmfiles referenced with `git::`

### ISSUE THREAD

**Issue by pintomic** [jenkins-x/jx-gitops#705]
Using remote helmfile like this:
```yaml
environments:
  default:
    values:
    - jx-values.yaml
namespace: kiam-test
helmfiles:
  - path: git::https://github.com/cloudposse/helmfiles.git@releases/kiam.yaml?ref=0.40.0
templates: {}
renderedvalues: {}
```

leads to following error during `jx gitops helmfile resolve` step:
```
error: failed to : failed to gather nested helmfiles: failed to get nested helmfiles helmfiles/kiam-test/helmfile.yaml in : failed to find nested helmfile helmfiles/kiam-test/git::https:/github.com/cloudposse/helmfiles.git@releases/kiam.yaml?ref=0.40.0
```
